spring.application.name=naval
server.port=8080

# MongoDB Atlas
spring.data.mongodb.uri=mongodb+srv://nathimuro12_db_user:RMd6Aqc4VEZWMODF@cluster0.fahuoad.mongodb.net/naval?appName=Cluster0

# JWT
jwt.secret=naval-secret-key-2026-proyecto-dam
jwt.expiration=86400