spring.application.name=naval
server.port=8080

spring.data.mongodb.uri=mongodb+srv://naval:Naval2026@cluster0.ezl9rel.mongodb.net/naval?appName=Cluster0

jwt.secret=naval-secret-key-2026-proyecto-dam
jwt.expiration=86400

server.error.include-message=always